### ISSUE TITLE
main-next is failing to compile due to missing Redis related Apache Geode properties

### ISSUE THREAD

**Issue by upthewaterspout** [spring-projects/spring-data-geode#592]
The main-next branch is failing to compile with the below error. This is likely due to changes made to geode in [GEODE-10126](https://issues.apache.org/jira/browse/GEODE-10126), where these Geode properties were removed. In Geode these properties were [marked experimental in Geode 1.14](https://geode.apache.org/releases/latest/javadoc/org/apache/geode/distributed/ConfigurationProperties.html#REDIS_ENABLED), so removing them was not considered a breaking change. Spring Data Geode should remove references to these properties for the next release that is intended to work with Geode 1.15.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (java-compile) on project spring-data-geode: Compilation failure: Compilation failure: 
[ERROR] /Users/upthewaterspout/Documents/Code/spring-data-geode/spring-data-geode/src/main/java/org/springframework/data/gemfire/GemFireProperties.java:[103,43] error: cannot find symbol
[ERROR]   symbol:   variable GEODE_FOR_REDIS_BIND_ADDRESS
[ERROR]   location: interface ConfigurationProperties
[ERROR] /Users/upthewaterspout/Documents/Code/spring-data-geode/spring-data-geode/src/main/java/org/springframework/data/gemfire/GemFireProperties.java:[104,38] error: cannot find symbol
[ERROR]   symbol:   variable GEODE_FOR_REDIS_ENABLED
[ERROR]   location: interface ConfigurationProperties
[ERROR] /Users/upthewaterspout/Documents/Code/spring-data-geode/spring-data-geode/src/main/java/org/springframework/data/gemfire/GemFireProperties.java:[105,35] error: cannot find symbol
[ERROR]   symbol:   variable GEODE_FOR_REDIS_PORT
[ERROR]   location: interface ConfigurationProperties
[ERROR] /Users/upthewaterspout/Documents/Code/spring-data-geode/spring-data-geode/src/main/java/org/springframework/data/gemfire/GemFireProperties.java:[106,47] error: cannot find symbol
[ERROR]   symbol:   variable GEODE_FOR_REDIS_REDUNDANT_COPIES
[ERROR]   location: interface ConfigurationProperties
[ERROR] /Users/upthewaterspout/Documents/Code/spring-data-geode/spring-data-geode/src/main/java/org/springframework/data/gemfire/GemFireProperties.java:[107,39] error: cannot find symbol
[ERROR]   symbol:   variable GEODE_FOR_REDIS_USERNAME
[ERROR]   location: interface ConfigurationProperties
[ERROR] -> [Help 1]

```

**Comment by jxblum** [comment]
Curious why the Redis port property was removed.  Configuring the embedded Redis service port for which Apache Geode will listen for Redis client connections seems like a sensible property to me, particularly given systems may share the same port number, even if unlikely.

More likely, is the fact that users and customers alike will be running Apache Geode (and by extension, VMware GemFire) behind a corporate firewall, and will need to configure the ports of some of GemFire/Geode's embedded services, like Redis, or the HTTP service, and so on.

Thoughts?

**Comment by jxblum** [comment]
Additionally, if I remember correctly, the value of the Redis port property was used to enable or disable the embedded Redis (server) service.

It is the new thinking that the embedded Redis (server) service will be enabled by default if the new Redis module is included on the classpath of the Apache Geode server(s) in the cluster?

It still might advise that even if the Redis module is on the classpath of the Geode servers in the cluster, that users/(GemFire) customers might still want a way to (conditionally) disable the embedded Redis service in certain uses case while leaving the configuration of their Geode server(s) (e.g. classpath) unchanged.

It certainly should be possible to start and stop the embedded Redis service without necessarily staring and stop the GemFire/Geode node (server) in which the embedded Redis service is running.  How does a user/customer do this?

**Comment by upthewaterspout** [comment]
Also, there is currently a discussion about removing geode-for-redis completely from apache Geode - see this thread - https://lists.apache.org/thread/7m23h9r0tf536g414bwjsplqh1qv2ct0 .

**Comment by jxblum** [comment]
SDG supports an Apache Geode server in the capacity as a Redis server using (enabling) the embedded Redis service, so these properties (and the corresponding support in SDG using the `@EnableRedisServer` annotation; see [docs](https://docs.spring.io/spring-data/geode/docs/current/reference/html/#bootstrap-annotation-config-embedded-services-redis)), cannot simply be removed.

Rather, SDG must now optionally include the new Redis module dependency, which is?

Would this be `org.apache.geode:geode-for-redis`, and matching the version of Geode (perhaps, `1.15.0`)?

Is there a GitHub repo or README that talks about how to use the new Redis module?

Sorry, I am currently sifting through all of this now.

**Comment by jxblum** [comment]
So, it seemed as though this worked for the time being:


```xml
		<dependency>
			<groupId>org.apache.geode</groupId>
			<artifactId>geode-for-redis</artifactId>
			<version>${geode.version}</version>
			<optional>true</optional>
		</dependency>
```

**Comment by jxblum** [comment]
Why is the `org.apache.geode.redis.internal.RedisConfiguration` class "internal"?

This is starting to look like a code smell to me.
